### ISSUE TITLE
[Bug]: Not recognize Queue facade :: assertPushed method

### ISSUE THREAD

**Issue by kamil-jakubowski** [laravel-idea/plugin#1018]
### Bug description

<img width="891" alt="image" src="https://github.com/laravel-idea/plugin/assets/4580210/1c585fec-754b-4cc9-8926-b07cdf2d6e68">

Laravel 5.4

### Plugin version

8.1.4.241

### Operating system

MacOS

**Comment by adelf** [comment]
After calling `Queue::fake()` the Queue facade suddenly becomes the facade for the `\Illuminate\Support\Testing\Fakes\QueueFake` class. I can't complete these methods in all cases since they are available only after calling the `fake()` method.

You can use this correct way:

<img width="464" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/a6dc16b6-5cca-4fec-8286-d67155815362">

**Comment by kamil-jakubowski** [comment]
Ah, ok make sense, my bad, sorry it was late night and I haven't thought that assertion functions aren't in the main Queue facade 🤦 

Unfortunately in lravel 5.4 Queue::fake() does not return anything, so I cannot use your proposal for autocompletion.
<img width="664" alt="image" src="https://github.com/laravel-idea/plugin/assets/4580210/13b6c016-4531-4ac8-8623-88e1817fb817">


Thanks for the answer and for the plugin, it really helps working with legacy laravel app 👍 🙏
