### ISSUE TITLE
Add support for Blade::componentNamespace()

### ISSUE THREAD

**Issue by inxilpro** [laravel-idea/plugin#194]
A Laravel plugin can register blade components using the following syntax (see [manually registering package components](https://laravel.com/docs/8.x/blade#manually-registering-package-components)):

```php
Blade::componentNamespace('Vendor\\PluginName\\Components', 'plugin-name');
```

By doing so, all components in the `Vendor\PluginName\Components` namespace will be discoverable with the `<x-plugin-name::` prefix.

For example:

- `Vendor\PluginName\Components\Foo` = `<x-plugin-name::foo />`
- `Vendor\PluginName\Components\Bar\Baz` = `<x-plugin-name::bar.baz />`

Currently the plugin seems to pick up components loaded with `loadViewComponentsAs()` but not with `componentNamespace()`.

**Comment by adelf** [comment]
I'll add. Thanks.

**Comment by adelf** [comment]
4.0 version is available.

**Comment by lthi747** [comment]
I cannot make this working. Is there something special other that need to be done?

```php
namespace priv1\Components;
use Illuminate\Support\Facades\Blade;
use Illuminate\Support\ServiceProvider;

class ComponentsServiceProvider extends ServiceProvider
{
    public function boot()
    {
        Blade::componentNamespace(
            '\\priv1\\Components\\View\\Components',
            'branded'
        );
    }
}
```

this is what i have

**Comment by adelf** [comment]
@lthi747, could you share some additional information?
Where is this "priv1\Components" namespace located? Some folder outside the project? Or?

**Comment by lthi747** [comment]
@adelf it's a package that I am reusing. I have created a composer package called priv1/Components and installed as a dependency into my project. Then in my project I am loading the service provider in my bootstrap.

Basically
/myproject (holds the current working project)
/myproject/bootstrap/providers.php (load the vendored components service provider)
/myproject/vendor/priv/Components (holds the package with components)
/myproject/app/View/Components (i am trying to use here and it works, but the phpstorm doesn't autocomplete them)

**Comment by lthi747** [comment]
@adelf is there any verbose or logs about how this feature works. I found that it works from times to times, and if I defined two namespaces in same file it works for second one but not for first. Also if it got works, it works for day or two then it stops

**Comment by adelf** [comment]
It tries to find a folder where this namespace is located and then works with this folder. It can work weird sometimes. Could you share your configuration? `componentNamespace` calls, directories and composer.json if your configuration isn't standard for Laravel apps.

**Comment by lthi747** [comment]
@adelf I think I found the reason but not sure how to proceed.

- I am using it in a "monorepo", where my app is in own directory
- I also have a packages directory

so
```
- /myapp (here is the larvel installation)
  -  .. composer.json 
- /packages (here is my components package)
  - private packages one per directory
```

in the composer.json in my app i have described "repositories" using "path" type simple as

```
"repositories": [
        {
            "type": "path",
            "url": "../packages/*",
            "options": {
                "symlink": false
            }
        }
    ]
```

then in my app i have regular require and composer update is found package, components works just fine.

So in general, i have two places where my module exists
/myapp/vendor/lhorg/components (this is copy of the content in the packages)
/packages/lhorg-components

if after the composer install/update i go and remove /packages/lhorg-components and restart the PHPStorm, then after that the autocomplete works and all my components are recognized.

Then if i undo the delete and restart phpstorm, these components are now appearing twice. But if I then invalidate caches and restart phpstorm, none is working again, so i need to repeat the delete process.

And this is working obviously only when i disable symlink in "repositories".

I tried to add the ./packages as excluded directory but it doesn't helps.

I hope that helps because is very weird behavior

**Comment by lthi747** [comment]
@adelf 

I just found one more quirk in the behavior. By some reason when Blade::componentNamespace() point to namespace that does not have file in the expected folder (located from composer.json) it does not load the components list, so need at least one component on that folder. For example

/packages/lhorg-components/src/Components contains just folders like (Form, Layout, Typography, etc.) and in these folders i have my components separated, so needed to place a dummy component in the root dir with namespace like

```
<?php
namespace LHOrg/Components;
class Dummy {}
```

I really with this functionality be not so picky because currently need to do few "hacks" just to have completion.

**Comment by adelf** [comment]
Yes, the logic isn't correct. It tries to find a directory for the namespace and fails sometimes.
I changed it. It will find all classes with this namespace prefix, so it should work correctly starting from the next update.
Thank you.
