### ISSUE TITLE
[Bug]: @class Blade directive no longer works after updating yesterday

### ISSUE THREAD

**Issue by smares** [laravel-idea/plugin#415]
### Bug description

After updating to 4.4.1.212 yesterday, the `@class` directive in Blade files no longer works and `@class` is treated like any other HTML attribute. Besides that, I am getting "Tag start is not closed" errors on every `@class` occurrence.

Already tried my usual "fixes" involving opening the settings, navigating to Languages & Frameworks -> Laravel Idea and hitting OK (this always magically fixes my problems where Laravel Idea is no longer able to find views or Blade components).

Also tried invalidating caches, but no luck.

### Plugin version

4.4.1.212

### Operating system

Windows

**Comment by adelf** [comment]
Hi, Sebastian. I had to temporarily turn off `@class` support because of this - https://youtrack.jetbrains.com/issue/WEB-52661
If your IDE works ok you can add it by self: Settings > PHP > Blade > Directives and create new one. `@class` with parameter and prefix code: `<?php echo \\Illuminate\\Support\\Arr::toCssClasses(` and suffix `)?>`

**Comment by adelf** [comment]
Fixed in the last PhpStorm. And @class returned back.
