### ISSUE TITLE
[Feature Request]: Provide generation for more than one package

### ISSUE THREAD

**Issue by maicol07** [laravel-idea/plugin#474]
### Feature Description

I've found out that I can't generate code (i.e. models) in a monorepo that contains multiple packages in a folder. It would be great if Laravel Idea supports monorepos with this format!

**Comment by adelf** [comment]
Do you mean several Laravel projects in the same PhpStorm project?

**Comment by maicol07** [comment]
@adelf no, I mean several Laravel packages in the same PHPStorm project

**Comment by maicol07** [comment]
You can check my monorepo (currently there is only one package, but I'm creating the second one and I saw this feature was missing): https://github.com/maicol07/osm_standard_modules

**Comment by adelf** [comment]
Laravel Idea currently can work only with 1 Laravel package/project inside PhpStorm project.

**Comment by adelf** [comment]
I don't think it will be implemented in the nearest future. And probably it will never happen.
For example, I ask PhpStorm "give me all Eloquent model class child classes in this project" and then I can work with them. But if there will be several projects I have to filter each model for each Laravel project. And something like this will happen for **each** action. 

Monorep is only about git. You can create a PhpStorm project per package and work. If you want to open all these packages... that means they aren't so independent, so maybe they shouldn't be separated?

**Comment by maicol07** [comment]
Mmm... maybe you're right. I currently use a monorepo for Composer purposes, but now that I think about it, I can easily transform the monorepo into a Composer metapackage and install the other ones

**Comment by adelf** [comment]
I'll close this for now. But if you have new ideas, you're welcome to share them here. 👍

**Comment by therecluse26** [comment]
This is necessary enough that PHPStorm added monorepo support by allowing multiple composer.json files in subdirectories after many years of devs asking for it. https://youtrack.jetbrains.com/issue/WI-39151

Monorepos are extremely common for microservice-based platforms, and it's not helpful to tell them "if they have overlapping functionality, maybe they should be a monolith." That's just not a practical response to the situation for many dev teams, and it's often not even a viable technical solution. 

Is converting a simple string directory to an array of directories and iterating over them to generate helper code for each a really big lift? Do you need help moving that over the line, because I'd be happy to help in any way.
