### ISSUE TITLE
[Bug]: incorrect migration code generation

### ISSUE THREAD

**Issue by medvinator** [laravel-idea/plugin#508]
### Bug description

Please [set anonymous migration](https://github.com/laravel/framework/pull/37352) in Laravel 9.x

Instead of this 
```php
class CreateProjectsTable extends Migration
{
```

It should be like this 
```php
return new class extends Migration
{
```

### Plugin version

5.1.1.213

### Operating system

Windows

**Comment by adelf** [comment]
Hi, Aleksandr.

Anonymous migrations will be created if you check a special "Anonymous" option. Old-style migrations are still supported, so I can't remove this option and leave only anonymous ones.

**Comment by medvinator** [comment]
Hello, Adel

> if you check a special "Anonymous" option

Sorry, I didn't mention what this behavior is when the model is created and the "Create migration" option is checked.

> I can't remove this option and leave only anonymous ones

You can detect version of `laravel/framework` package from **composer.json** and change behavior depending on this version 😊

**Comment by adelf** [comment]
I use the current Laravel version a lot. But I can't use only anonymous for every Laravel 9 project. 

You can create anonymous migration once and then it will create only anonymous migrations. I'll try to find a way to make it more convenient for "Create Model" migration. Thank you for posting.

**Comment by andrey-helldar** [comment]
Lumen 6

This code will not work because an anonymous migration is being created.

![image](https://user-images.githubusercontent.com/10347617/173829023-d42a754b-5af7-4f2d-bc7e-d22d3d4a6b3c.png)

![image](https://user-images.githubusercontent.com/10347617/173829080-be94a899-02cd-46ae-9e6c-b585e070edd0.png)

![image](https://user-images.githubusercontent.com/10347617/173829251-8c56291c-0ff4-417c-9952-dab3b33db4e5.png)

**Comment by adelf** [comment]
@andrey-helldar fixed. Thanks.

BTW, I can close this after releasing the new version since the "anonymous" option is true by default now.
