### ISSUE TITLE
Does pugin supports lumen router?

### ISSUE THREAD

**Issue by andrew-svirin** [laravel-idea/plugin#59]
I have not autocompletition and navigation to cntroller actions like it works for laravel.

My router file:
```<?php

use Laravel\Lumen\Routing\Router;

/* @var $router Router */

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It is a breeze. Simply tell Lumen the URIs it should respond to
| and give it the Closure to call when that URI is requested.
|
*/

$router->get('/', function () use ($router) {
    return 'API';
});

$router->group([
    'prefix' => 'api',
], function () use ($router) {
    $router->get('version', [
        'uses' => 'SiteController@version',
    ]);
});
```

**Comment by adelf** [comment]
Hi. 
Please, make sure that plugin detected lumen, like here:

![image](https://user-images.githubusercontent.com/2818394/82591761-7f410500-9ba8-11ea-9386-14f3104ccffd.png)

Then, it analyzes bootstrap/app.php file to get information about route files. Have you changed it?
Next possible reason is base class for controllers. Due to performance reasons I had to fetch only classes inherited from it. Maybe I should implement more smart controller class fetching...

Actually, if plugin works, it provides type for $router variable and this code is unneded: 
```
use Laravel\Lumen\Routing\Router;

/* @var $router Router */
```
