### ISSUE TITLE
What about livewire/nova support ?

### ISSUE THREAD

**Issue by Insolita** [laravel-idea/plugin#70]
Have you thoughts to add support nova or livewire? Seems livewire becomes a new trend. Or you have scoped the laravel only,  without third-party plugins?

**Comment by adelf** [comment]
I have a whole settings page about third party packages ;) but currently there are only bladeX.
Ok. Livewire - definitely. I hope to release 3.1 version next week and going to include first draft of livewire support there.
I’m not sure about Nova since I never used it, but if you have ideas about completions or other support you’re very welcome.

**Comment by Insolita** [comment]
It sounds really good!  
About the Nova, it has a lot of own console generators and will be more useful to have the ability to call it in the same way from GUI hot-key. Also, it can be optionally improved with advanced Resource stub generation with fields based on db columns

**Comment by Insolita** [comment]
if you need more information about nova - send me a direct message on twitter

**Comment by adelf** [comment]
3.1 version with livewire support is online. I also created "nova support" item in my Trello. So, closing this.
