### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by spyworldxp** [laravel-idea/plugin#872]
### Bug description

```
View::make('template.index');
```
Unable to recognize the view template link in "Laravel 4.2" means can't click and open the template/index.blade.php

### Plugin version

7.4.3.232

### Operating system

None

**Comment by adelf** [comment]
For Laravel 4.2 you can change the Default views path to "app/views" and, if you use ".php" templates instead of ".blade.php" you can also add ".php" to "View files suffixes". And everything will work.

<img width="892" alt="image" src="https://github.com/laravel-idea/plugin/assets/2818394/45e02fce-3780-4dea-95f3-885cad84c443">
