### ISSUE TITLE
[Bug]: berkayk/onesignal-laravel facade not being recognized

### ISSUE THREAD

**Issue by walterdis** [laravel-idea/plugin#944]
### Bug description

Hello,

I'm currently using the `berkayk/onesignal-laravel` package in my Laravel project. However, I'm facing an issue where the Laravel IDE isn't auto-completing the facade methods for this package.

Interestingly, when I use the `barryvdh/laravel-ide-helper` package, the auto-completion works as expected.

Could you please provide some guidance on how to resolve this issue with the `berkayk/onesignal-laravel` package so that the Laravel IDE can auto-complete the facade methods?

Thank you.

![image](https://github.com/laravel-idea/plugin/assets/1938830/00923cfc-04aa-4984-a718-7300b7b6016b)

### Operating system

None

**Comment by adelf** [comment]
Hello. Sorry for late response.

You can add "@see \...\OneSignalClient" phpDoc to the facade class, and it will work.

**Comment by walterdis** [comment]
Hi, thx for the answer ;)
I'm not the one who maintains the package or, there's another way to do it?

**Comment by Fludem** [comment]
Hey,

Maybe he can do something, but this is kind of a one-off, honestly, as most packages work except this.

There is an open pull request from almost 3 years ago to add the @see and other phpDocs to the facade class here, but they've been ignored:

https://github.com/berkayk/laravel-onesignal/pull/153

There are a ton of open PRs and issues, and they need to be maintained better. I suggest copying all of these files into your project, honestly.

You can either hard copy or create a fork of the project and symlink it as a package.

It's not usually regarded as best practice due to missing out on updates and increasing the code you have to maintain.

But this is 3 files and you won't be missing out on many updates.

**Comment by walterdis** [comment]
> Hey,
> 
> Maybe he can do something, but this is kind of a one-off, honestly, as most packages work except this.
> 
> There is an open pull request from almost 3 years ago to add the @see and other phpDocs to the facade class here, but they've been ignored:
> 
> [berkayk/laravel-onesignal#153](https://github.com/berkayk/laravel-onesignal/pull/153)
> 
> There are a ton of open PRs and issues, and they need to be maintained better. I suggest copying all of these files into your project, honestly.
> 
> You can either hard copy or create a fork of the project and symlink it as a package.
> 
> It's not usually regarded as best practice due to missing out on updates and increasing the code you have to maintain.
> 
> But this is 3 files and you won't be missing out on many updates.

You're right ;)

I'll give it a try.
Thank you

**Comment by adelf** [comment]
I'll also try to implement facade classes fetching from strings like 'onesignal'.
